### PR TITLE
reorganize type hints, remove all reflection

### PR DESCRIPTION
**Pull request by MichaelBlume**

### CODE REVIEW

**Comment by MichaelBlume** [comment]
Before:
```
$ lein check
Compiling namespace image-resizer.core
Reflection warning, image_resizer/util.clj:10:5 - call to read can't be resolved.
Reflection warning, image_resizer/util.clj:13:4 - reference to field getWidth can't be resolved.
Reflection warning, image_resizer/util.clj:13:22 - reference to field getHeight can't be resolved.
Reflection warning, image_resizer/resize.clj:16:8 - call to resize can't be resolved.
Reflection warning, image_resizer/resize.clj:22:8 - call to resize can't be resolved.
Reflection warning, image_resizer/resize.clj:34:8 - call to resize can't be resolved.
Reflection warning, image_resizer/core.clj:9:4 - reference to field getWidth can't be resolved.
Reflection warning, image_resizer/core.clj:9:22 - reference to field getHeight can't be resolved.
Compiling namespace image-resizer.crop
Compiling namespace image-resizer.dimensions
Compiling namespace image-resizer.format
Reflection warning, image_resizer/format.clj:12:22 - call to java.io.File ctor can't be resolved.
Reflection warning, image_resizer/format.clj:13:5 - call to write can't be resolved.
Reflection warning, image_resizer/format.clj:20:5 - call to write can't be resolved.
Compiling namespace image-resizer.fs
Compiling namespace image-resizer.modes
Compiling namespace image-resizer.ops
Compiling namespace image-resizer.pad
Compiling namespace image-resizer.resize
Reflection warning, image_resizer/resize.clj:16:8 - call to resize can't be resolved.
Reflection warning, image_resizer/resize.clj:22:8 - call to resize can't be resolved.
Reflection warning, image_resizer/resize.clj:34:8 - call to resize can't be resolved.
Compiling namespace image-resizer.rotate
Compiling namespace image-resizer.scale-methods
Compiling namespace image-resizer.util
Reflection warning, image_resizer/util.clj:10:5 - call to read can't be resolved.
Reflection warning, image_resizer/util.clj:13:4 - reference to field getWidth can't be resolved.
Reflection warning, image_resizer/util.clj:13:22 - reference to field getHeight can't be resolved.
```

After:
```
$ lein check
Compiling namespace image-resizer.core
Compiling namespace image-resizer.crop
Compiling namespace image-resizer.dimensions
Compiling namespace image-resizer.format
Compiling namespace image-resizer.fs
Compiling namespace image-resizer.modes
Compiling namespace image-resizer.ops
Compiling namespace image-resizer.pad
Compiling namespace image-resizer.resize
Compiling namespace image-resizer.rotate
Compiling namespace image-resizer.scale-methods
Compiling namespace image-resizer.util
```

**Comment by MichaelBlume** [comment]
Ping?

**Comment by josephwilk** [comment]
Sorry, I missed this. Looks good, thank you!

**Comment by josephwilk** [comment]
0.1.8 Cut and released with this change. Thanks!

**Pull request merged**
